#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="1"
    ACTUAL=$("$PROGRAM" -e '0 cos p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test empty stack
    EXPECTED="'cos' requires one operand"
    ACTUAL=$("$PROGRAM" -e 'cos' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test non numerical values
    EXPECTED="'cos' requires numeric values"
    ACTUAL=$("$PROGRAM" -e '[ foo ] cos' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
