#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="3.14159"
    ACTUAL=$("$PROGRAM" -e '5 k pi p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test default precision
    EXPECTED="0"
    ACTUAL=$("$PROGRAM" -e 'K p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test invalid precision
    EXPECTED="Precision must be a non-negative number"
    ACTUAL=$("$PROGRAM" -e '-1 k' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
