#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="4"
    ACTUAL=$("$PROGRAM" -e '5 4 3 1 z p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test empty stack
    PROGRAM="$PWD/build/dc"
    EXPECTED="0"
    ACTUAL=$("$PROGRAM" -e 'z p')
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
