#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="18"
    ACTUAL=$("$PROGRAM" -e '6 3 * p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test empty stack
    EXPECTED="'*' requires two operands"
    ACTUAL=$("$PROGRAM" -e '*' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test non numerical values
    EXPECTED="'*' requires numeric values"
    ACTUAL=$("$PROGRAM" -e '[ foo ] 5 *' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test complex values
    EXPECTED="(13,-18)"
    ACTUAL=$("$PROGRAM" -e '2 -5 b 4 1 b * p')
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
