#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="1111111111111111111111111111111111111111111111111111111111111101b"
    ACTUAL=$("$PROGRAM" -e '2 d i o 10 l p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test empty stack
    EXPECTED="'l' requires one operand"
    ACTUAL=$("$PROGRAM" -e 'l' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test non numerical values
    EXPECTED="'l' requires numeric values"
    ACTUAL=$("$PROGRAM" -e '[ foo ] l' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
