#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="0.67"
    ACTUAL=$("$PROGRAM" -e '0.79 atan p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test empty stack
    EXPECTED="'atan' requires one operand"
    ACTUAL=$("$PROGRAM" -e 'atan' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test non numerical values
    EXPECTED="'atan' requires numeric values"
    ACTUAL=$("$PROGRAM" -e '[ foo ] atan' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
