#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="0"
    ACTUAL=$("$PROGRAM" -e '0 tan p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test empty stack
    EXPECTED="'tan' requires one operand"
    ACTUAL=$("$PROGRAM" -e 'tan' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test non numerical values
    EXPECTED="'tan' requires numeric values"
    ACTUAL=$("$PROGRAM" -e '[ foo ] tan' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
