#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="500"
    ACTUAL=$("$PROGRAM" -e '10 d 500 r :A ;A p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test empty stack
    EXPECTED="This operation requires one value"
    ACTUAL=$("$PROGRAM" -e ';A' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
