#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="25 20 15 10 5"
    ACTUAL=$("$PROGRAM" -e '5 10 15 20 25 f' | tr '\n' ' ' | sed 's/ $/\n/')
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
