#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="0b"
    ACTUAL=$("$PROGRAM" -e '2 d i o 10 10 L p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test empty stack
    EXPECTED="'L' requires two operands"
    ACTUAL=$("$PROGRAM" -e 'L' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test non numerical values
    EXPECTED="'L' requires numeric values"
    ACTUAL=$("$PROGRAM" -e '5 [ foo ] L' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
