#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="3.141592653589793"
    ACTUAL=$("$PROGRAM" -e '15 k pi p')
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
