#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="0"
    ACTUAL=$("$PROGRAM" -e '0 sin p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test empty stack
    EXPECTED="'sin' requires one operand"
    ACTUAL=$("$PROGRAM" -e 'sin' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test non numerical values
    EXPECTED="'sin' requires numeric values"
    ACTUAL=$("$PROGRAM" -e '[ foo ] sin' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
