#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="276"
    ACTUAL=$("$PROGRAM" -e '24 2 gC p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test empty stack
    EXPECTED="'gC' requires two operands"
    ACTUAL=$("$PROGRAM" -e 'gC' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test non numerical values
    EXPECTED="'gC' requires integer values"
    ACTUAL=$("$PROGRAM" -e '[ foo ] 5 gC' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
