#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="1.57"
    ACTUAL=$("$PROGRAM" -e '.99999967 asin p')
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test empty stack
    EXPECTED="'asin' requires one operand"
    ACTUAL=$("$PROGRAM" -e 'asin' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test non numerical values
    EXPECTED="'asin' requires numeric values"
    ACTUAL=$("$PROGRAM" -e '[ foo ] asin' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
