#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    ACTUAL=$("$PROGRAM" -e '-10 10 @ $ p')
    assert_ge "$ACTUAL" "-10"
    assert_le "$ACTUAL" "10"

    # Test empty stack
    EXPECTED="'@' requires two operands"
    ACTUAL=$("$PROGRAM" -e '@' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"

    # Test non numerical values
    EXPECTED="'@' requires numeric values"
    ACTUAL=$("$PROGRAM" -e '[ foo ] 5 @' 2>&1) || true
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
