#!/bin/sh

utest() {
    PROGRAM="$PWD/build/dc"
    EXPECTED="2.718281828459045"
    ACTUAL=$("$PROGRAM" -e '15 k e p')
    assert_eq "$EXPECTED" "$ACTUAL"
}
# vim: ts=4 sw=4 softtabstop=4 expandtab:
