name: dc
on:
  push:
    branches: [master, factory_parsing]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Build dc
      run: |
        apt -y update && apt -y install cmake build-essential
        mkdir build && cd build
        cmake ..
        make
    - name: Run unit tests
      run: |
        ./utest.sh tests
