name: dc
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Build dc
      run: |
        apt -y update && apt -y install cmake build-essential
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug .
        cmake --build build
    - name: Run unit tests
      run: |
        ./utest.sh tests
