name: dc
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Install dependencies
      run: |
        sudo apt -y update && sudo apt -y install cmake ninja-build build-essential
    - name: Build DC
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release .
        cmake --build build
    - name: Run unit tests
      run: |
        ./utest.sh tests
